<?php 
	$sehir = array(
	'1' =>'Adana',
	'2' =>'Adıyaman',
	'3' =>'Afyonkarahisar',
	'4' =>'Ağrı',
	'5' =>'Amasya',
	'6' =>'Ankara',
	'7' =>'Antalya',
	'8' =>'Artvin',
	'9' =>'Aydın',
	'10' =>'Balıkesir',
	'11' =>'Bilecik',
	'12' =>'Bingöl',
	'13' =>'Bitlis',
	'14' =>'Bolu',
	'15' =>'Burdur',
	'16' =>'Bursa',
	'17' =>'Çanakkale',
	'18' =>'Çankırı',
	'19' =>'Çorum',
	'20' =>'Denizli',
	'21' =>'Diyarbakır',
	'22' =>'Edirne',
	'23' =>'Elâzığ',
	'24' =>'Erzincan',
	'25' =>'Erzurum',
	'26' =>'Eskişehir',
	'27' =>'Gaziantep',
	'28' =>'Giresun',
	'29' =>'Gümüşhane',
	'30' =>'Hakkari',
	'31' =>'Hatay',
	'32' =>'Isparta',
	'33' =>'Mersin',
	'34' =>'İstanbul',
	'35' =>'İzmir',
	'36' =>'Kars',
	'37' =>'Kastamonu',
	'38' =>'Kayseri',
	'39' =>'Kırklareli',
	'40' =>'Kırşehir',
	'41' =>'Kocaeli',
	'42' =>'Konya',
	'43' =>'Kütahya',
	'44' =>'Malatya',
	'45' =>'Manisa',
	'46' =>'Kahramanmaraş',
	'47' =>'Mardin',
	'48' =>'Muğla',
	'49' =>'Muş',
	'50' =>'Nevşehir',
	'51' =>'Niğde',
	'52' =>'Ordu',
	'53' =>'Rize',
	'54' =>'Sakarya',
	'55' =>'Samsun',
	'56' =>'Siirt',
	'57' =>'Sinop',
	'58' =>'Sivas',
	'59' =>'Tekirdağ',
	'60' =>'Tokat',
	'61' =>'Trabzon',
	'62' =>'Tunceli',
	'63' =>'Şanlıurfa',
	'64' =>'Uşak',
	'65' =>'Van',
	'66' =>'Yozgat',
	'67' =>'Zonguldak',
	'68' =>'Aksaray',
	'69' =>'Bayburt',
	'70' =>'Karaman',
	'71' =>'Kırıkkale',
	'72' =>'Batman',
	'73' =>'Şırnak',
	'74' =>'Bartın',
	'75' =>'Ardahan',
	'76' =>'Iğdır',
	'77' =>'Yalova',
	'78' =>'Karabük',
	'79' =>'Kilis',
	'80' =>'Osmaniye',
	'81' =>'Düzce',
	);


	$ilceler['34']['1'] = "Adalar";
	$ilceler['34']['2'] = "Arnavutköy";
	$ilceler['34']['3'] = "Ataşehir";
	$ilceler['34']['4'] = "Avcılar";
	$ilceler['34']['5'] = "Bağcılar";
	$ilceler['34']['6'] = "Bahçelievler";
	$ilceler['34']['7'] = "Bakırköy";
	$ilceler['34']['8'] = "Başakşehir";
	$ilceler['34']['9'] = "Bayrampaşa";
	$ilceler['34']['10'] = "Beşiktaş";
	$ilceler['34']['11'] = "Beylikdüzü";
	$ilceler['34']['12'] = "Beyoğlu";
	$ilceler['34']['13'] = "Büyükçekmece";
	$ilceler['34']['14'] = "Beykoz";
	$ilceler['34']['15'] = "Çatalca";
	$ilceler['34']['16'] = "Çekmeköy";
	$ilceler['34']['17'] = "Esenler";
	$ilceler['34']['18'] = "Esenyurt";
	$ilceler['34']['19'] = "Eyüp";
	$ilceler['34']['20'] = "Fatih";
	$ilceler['34']['21'] = "Gaziosmanpaşa";
	$ilceler['34']['22'] = "Güngören";
	$ilceler['34']['23'] = "Kadıköy";
	$ilceler['34']['24'] = "Kağıthane";
	$ilceler['34']['25'] = "Kartal";
	$ilceler['34']['26'] = "Küçükçekmece";
	$ilceler['34']['27'] = "Maltepe";
	$ilceler['34']['28'] = "Pendik";
	$ilceler['34']['29'] = "Sancaktepe";
	$ilceler['34']['30'] = "Sarıyer";
	$ilceler['34']['31'] = "Silivri";
	$ilceler['34']['32'] = "Sultanbeyli";
	$ilceler['34']['33'] = "Sultangazi";
	$ilceler['34']['34'] = "Şile";
	$ilceler['34']['35'] = "Şişli";
	$ilceler['34']['36'] = "Tuzla";
	$ilceler['34']['37'] = "Üsküdar";
	$ilceler['34']['38'] = "Ümraniye";
	$ilceler['34']['39'] = "Zeytinburnu";


	$ilceyakinlik['34']['Adalar'] = array('Adalar','Pendik','Sultanbeyli','Ataşehir');
	$ilceyakinlik['34']['Arnavutköy']=array('Arnavutköy','Başakşehir','Çatalca','Esenyurt');
	$ilceyakinlik['34']['Ataşehir']=array('Ataşehir','Kadıköy','Sultanbeyli','Üsküdar');
	$ilceyakinlik['34']['Avcılar']=array('Avcılar','Esenyurt','Beylikdüzü','Büyükçekmece');
	$ilceyakinlik['34']['Bağcılar']=array('Bağcılar','Başakşehir','Küçükçekmece','Fatih');
	$ilceyakinlik['34']['Bahçelievler']=array('Bahçelievler','Bakırköy','Küçükçekmece','Zeytinburnu');
	$ilceyakinlik['34']['Bakırköy']=array('Bakırköy','Bahçelievler','Küçükçekmece','Zeytinburnu');
	$ilceyakinlik['34']['Başakşehir']=array('Başakşehir','Esenyurt','Arnavutköy','Küçükçekmece');
	$ilceyakinlik['34']['Bayrampaşa']=array('Bayrampaşa','Gaziosmanpaşa','Eyüp','Zeytinburnu');
	$ilceyakinlik['34']['Beşiktaş']=array('Beşiktaş','Şişli','Kağıthane','Beyoğlu');
	$ilceyakinlik['34']['Beylikdüzü']=array('Beylikdüzü','Avcılar','Büyükçekmece','Esenyurt');
	$ilceyakinlik['34']['Beyoğlu']=array('Beyoğlu','Kağıthane','Şişli','Beşiktaş');
	$ilceyakinlik['34']['Büyükçekmece']=array('Büyükçekmece','Beylikdüzü','Silivri','Çatalca');
	$ilceyakinlik['34']['Beykoz']=array('Beykoz','Şile','Çekmeköy','Üsküdar');
	$ilceyakinlik['34']['Çatalca']=array('Çatalca','Büyükçekmece','Silivri','Arnavutköy');
	$ilceyakinlik['34']['Çekmeköy']=array('Çekmeköy','Sultanbeyli','Beykoz','Üsküdar');
	$ilceyakinlik['34']['Esenler']=array('Esenler','Bayrampaşa','Güngören','Zeytinburnu');
	$ilceyakinlik['34']['Esenyurt']=array('Esenyurt','Büyükçekmece','Avcılar','Küçükçekmece');
	$ilceyakinlik['34']['Eyüp']=array('Eyüp','Fatih','Sarıyer','Çatalca');
	$ilceyakinlik['34']['Fatih']=array('Fatih','Zeytinburnu','Eyüp','Bağcılar');
	$ilceyakinlik['34']['Gaziosmanpaşa']=array('Gaziosmanpaşa','Sultangazi','Eyüp','Şişli');
	$ilceyakinlik['34']['Güngören']=array('Güngören','Bakırköy','Zeytinburnu','Fatih');
	$ilceyakinlik['34']['Kadıköy']=array('Kadıköy','Ataşehir','Üsküdar','Fatih');
	$ilceyakinlik['34']['Kağıthane']=array('Kağıthane','Sarıyer','Beşiktaş','Beyoğlu');
	$ilceyakinlik['34']['Kartal']=array('Kartal','Pendik','Sultanbeyli','Ataşehir');
	$ilceyakinlik['34']['Küçükçekmece']=array('Küçükçekmece','Avcılar','Bahçelievler','Bakırköy');
	$ilceyakinlik['34']['Maltepe']=array('Maltepe','Kadıköy','Ataşehir','Sultanbeyli');
	$ilceyakinlik['34']['Pendik']=array('Pendik','Tuzla','Kartal','Maltepe');
	$ilceyakinlik['34']['Sancaktepe']=array('Sancaktepe','Sultanbeyli','Ataşehir','Ümraniye');
	$ilceyakinlik['34']['Sarıyer']=array('Sarıyer','Beşiktaş','Şişli','Arnavutköy');
	$ilceyakinlik['34']['Silivri']=array('Silivri','Büyükçekmece','Çatalca','Cerkezkoy');
	$ilceyakinlik['34']['Sultanbeyli']=array('Sultanbeyli','Sancaktepe','Pendik','Maltepe');
	$ilceyakinlik['34']['Sultangazi']=array('Sultangazi','Eyüp','Gaziosmanpaşa','Başakşehir');
	$ilceyakinlik['34']['Şile']=array('Şile','Pendik','Çekmeköy','Beykoz');
	$ilceyakinlik['34']['Şişli']=array('Şişli','Beşiktaş','Kağıthane','Beyoğlu');
	$ilceyakinlik['34']['Tuzla']=array('Tuzla','Pendik','Sultanbeyli','Beykoz');
	$ilceyakinlik['34']['Üsküdar']=array('Üsküdar','Beykoz','Ümraniye','Ataşehir');
	$ilceyakinlik['34']['Ümraniye']=array('Ümraniye','Üsküdar','Şile','Kadıköy');
	$ilceyakinlik['34']['Zeytinburnu']=array('Zeytinburnu','Bakırköy','Bahçelievler','Fatih');
?>