<?php 
$sehir = array(
'1' =>'Adana',
'2' =>'Adıyaman',
'3' =>'Afyonkarahisar',
'4' =>'Ağrı',
'5' =>'Amasya',
'6' =>'Ankara',
'7' =>'Antalya',
'8' =>'Artvin',
'9' =>'Aydın',
'10' =>'Balıkesir',
'11' =>'Bilecik',
'12' =>'Bingöl',
'13' =>'Bitlis',
'14' =>'Bolu',
'15' =>'Burdur',
'16' =>'Bursa',
'17' =>'Çanakkale',
'18' =>'Çankırı',
'19' =>'Çorum',
'20' =>'Denizli',
'21' =>'Diyarbakır',
'22' =>'Edirne',
'23' =>'Elâzığ',
'24' =>'Erzincan',
'25' =>'Erzurum',
'26' =>'Eskişehir',
'27' =>'Gaziantep',
'28' =>'Giresun',
'29' =>'Gümüşhane',
'30' =>'Hakkari',
'31' =>'Hatay',
'32' =>'Isparta',
'33' =>'Mersin',
'34' =>'İstanbul',
'35' =>'İzmir',
'36' =>'Kars',
'37' =>'Kastamonu',
'38' =>'Kayseri',
'39' =>'Kırklareli',
'40' =>'Kırşehir',
'41' =>'Kocaeli',
'42' =>'Konya',
'43' =>'Kütahya',
'44' =>'Malatya',
'45' =>'Manisa',
'46' =>'Kahramanmaraş',
'47' =>'Mardin',
'48' =>'Muğla',
'49' =>'Muş',
'50' =>'Nevşehir',
'51' =>'Niğde',
'52' =>'Ordu',
'53' =>'Rize',
'54' =>'Sakarya',
'55' =>'Samsun',
'56' =>'Siirt',
'57' =>'Sinop',
'58' =>'Sivas',
'59' =>'Tekirdağ',
'60' =>'Tokat',
'61' =>'Trabzon',
'62' =>'Tunceli',
'63' =>'Şanlıurfa',
'64' =>'Uşak',
'65' =>'Van',
'66' =>'Yozgat',
'67' =>'Zonguldak',
'68' =>'Aksaray',
'69' =>'Bayburt',
'70' =>'Karaman',
'71' =>'Kırıkkale',
'72' =>'Batman',
'73' =>'Şırnak',
'74' =>'Bartın',
'75' =>'Ardahan',
'76' =>'Iğdır',
'77' =>'Yalova',
'78' =>'Karabük',
'79' =>'Kilis',
'80' =>'Osmaniye',
'81' =>'Düzce',
);


$ilceler['34']['1'] = "Adalar";
$ilceler['34']['2'] = "Arnavutkoy";
$ilceler['34']['3'] = "Ataşehir";
$ilceler['34']['4'] = "Avcılar";
$ilceler['34']['5'] = "Bağcılar";
$ilceler['34']['6'] = "Bahçelievler";
$ilceler['34']['7'] = "Bakırköy";
$ilceler['34']['8'] = "Başakşehir";
$ilceler['34']['9'] = "Bayrampasa";
$ilceler['34']['10'] = "Beşiktaş";

$ilceler['34']['11'] = "Beylikdüzü";
$ilceler['34']['12'] = "Beyoğlu";
$ilceler['34']['13'] = "Büyükçekmece";
$ilceler['34']['14'] = "Beykoz";
$ilceler['34']['15'] = "Çatalca";
$ilceler['34']['16'] = "Çekmeköy";
$ilceler['34']['17'] = "Esenler";
$ilceler['34']['18'] = "Esenyurt";
$ilceler['34']['19'] = "Eyüp";
$ilceler['34']['20'] = "Fatih";
$ilceler['34']['21'] = "Gaziosmanpaşa";
$ilceler['34']['22'] = "Güngören";
$ilceler['34']['23'] = "Kadıköy";
$ilceler['34']['24'] = "Kağıthane";
$ilceler['34']['25'] = "Kartal";
$ilceler['34']['26'] = "Küçükçekmece";
$ilceler['34']['27'] = "Maltepe";
$ilceler['34']['28'] = "Pendik";
$ilceler['34']['29'] = "Sancaktepe";
$ilceler['34']['30'] = "Sarıyer";
$ilceler['34']['31'] = "Silivri";
$ilceler['34']['32'] = "Sultanbeyli";
$ilceler['34']['33'] = "Sultangazi";
$ilceler['34']['34'] = "Şile";
$ilceler['34']['35'] = "Şişli";
$ilceler['34']['36'] = "Tuzla";
$ilceler['34']['37'] = "Üsküdar";
$ilceler['34']['38'] = "Ümraniye";
$ilceler['34']['39'] = "zeytinburnu";


$ilceyakinlik['34']['Adalar'] = array('pendik','sultanbeyli','atasehir');
$ilceyakinlik['34']['Arnavutkoy']=array('basaksehir','catalca','esenyurt');
$ilceyakinlik['34']['Atasehir']=array('kadikoy','sultanbeyli','uskudar');
$ilceyakinlik['34']['Avcilar']=array('esenyurt','beylikduzu','buyukcekmece');
$ilceyakinlik['34']['Bagcilar']=array('basaksehir','kucukcekmece','fatih');
$ilceyakinlik['34']['Bahcelievler']=array('bakirkoy','kucukcekmece','zeytinburnu');
$ilceyakinlik['34']['Bakirkoy']=array('bahcelievler','kucukcekmece','zeytinburnu');
$ilceyakinlik['34']['Basaksehir']=array('esenyurt','arnavutkoy','kucukcekmece');
$ilceyakinlik['34']['Bayrampasa']=array('gaziosmanpasa','eyup','zeytinburnu');
$ilceyakinlik['34']['Besiktas']=array('sisli','kagithane','beyoglu');
$ilceyakinlik['34']['Beylikdüzü']=array('avcilar','buyukcekmece','esenyurt');
$ilceyakinlik['34']['Beyoğlu']=array('kagithane','sisli','besiktas');
$ilceyakinlik['34']['Büyükçekmece']=array('beylikduzu','silivri','catalca');
$ilceyakinlik['34']['Beykoz']=array('sile','cekmekoy','uskudar');
$ilceyakinlik['34']['Çatalca']=array('buyukcekmece','silivri','arnavutkoy');
$ilceyakinlik['34']['Çekmeköy']=array('sultanbeyli','beykoz','uskudar');
$ilceyakinlik['34']['Esenler']=array('bayrampasa','gungoren','zeytinburnu');
$ilceyakinlik['34']['Esenyurt']=array('buyukcekmece','avcilar','kucukcekmece');
$ilceyakinlik['34']['Eyüp']=array('fatih','sariyer','catalca');
$ilceyakinlik['34']['Fatih']=array('zeytinburnu','eyup','bagcilar');
$ilceyakinlik['34']['Gaziosmanpaşa']=array('sultangazi','eyup','sisli');
$ilceyakinlik['34']['Güngören']=array('bakirkoy','zeytinburnu','fatih');
$ilceyakinlik['34']['Kadıköy']=array('atasehir','uskudar','fatih');
$ilceyakinlik['34']['Kağıthane']=array('sariyer','besiktas','beyoglu');
$ilceyakinlik['34']['Kartal']=array('pendik','sultanbeyli','atasehir');
$ilceyakinlik['34']['Küçükçekmece']=array('avcilar','bahcelievler','bakirkoy');
$ilceyakinlik['34']['Maltepe']=array('kadikoy','atasehir','sultanbeyli');
$ilceyakinlik['34']['Pendik']=array('tuzla','kartal','maltepe');
$ilceyakinlik['34']['Sancaktepe']=array('sultanbeyli','atasehir','umraniye');
$ilceyakinlik['34']['Sarıyer']=array('besiktas','sisli','arnavutkoy');
$ilceyakinlik['34']['Silivri']=array('buyukcekmece','catalca','cerkezkoy');
$ilceyakinlik['34']['Sultanbeyli']=array('sancaktepe','pendik','maltepe');
$ilceyakinlik['34']['Sultangazi']=array('eyup','gaziosmanpasa','basaksehir');
$ilceyakinlik['34']['Şile']=array('pendik','cekmekoy','beykoz');
$ilceyakinlik['34']['Şişli']=array('besiktas','kagithane','beyoglu');
$ilceyakinlik['34']['Tuzla']=array('pendik','sultanbeyli','beykoz');
$ilceyakinlik['34']['Üsküdar']=array('beykoz','umraniye','atasehir');
$ilceyakinlik['34']['Ümraniye']=array('uskudar','sile','kadikoy');
$ilceyakinlik['34']['zeytinburnu']=array('bakirkoy','bahcelievler','fatih');





?>